version: '3'

services:
  app:
    container_name: parkngo_dev
    restart: always
    build: .
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    container_name: mongo_parkngo
    image: mongo
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
       - data:/data/db

volumes:
  data:
